#!/bin/bash
set -e
# blender-base AMI
export BRENDA_AMI_ID=ami-61316d08
cd
if [ "$1" = "1" ]; then
	echo BRENDA RUN
	brenda-run -i t1.micro -I demand
elif [ "$1" = "2" ]; then
	echo BRENDA STATUS
	brenda-tool ssh uptime
elif [ "$1" = "3" ]; then
	echo BRENDA CLEAN
	cd ~/src/brenda
	./doclean
	cd ..
	echo REMOVE PREVIOUS
	brenda-tool ssh 'rm -rf brenda.tar.gz brenda'
	echo TAR
	tar cfzv brenda.tar.gz brenda
	echo PUSH TAR
	brenda-tool rsync brenda.tar.gz HOST:
	echo INSTALL BRENDA
	brenda-tool ssh 'tar xf brenda.tar.gz && cd brenda && python setup.py install && cd .. && rm -rf brenda.tar.gz brenda'
	echo RM ROOT SECURITY-SENSITIVE FILES
	brenda-tool ssh 'cd /home/ubuntu && rm -vf .bash_history && cd .ssh && rm -vf authorized_keys authorized_keys.bak'
	echo RM UBUNTU SECURITY-SENSITIVE FILES and SHUTDOWN
	brenda-tool ssh 'rm -vf .bash_history && cd .ssh && rm -vf authorized_keys authorized_keys.bak && shutdown -h 0'
else
	echo "usage: brenda-ami 1|2|3"
fi
